In [2]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [3]:
import kagglehub

# Dow
path = kagglehub.dataset_download("prokshitha/home-value-insights")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'home-value-insights' dataset.
Path to dataset files: /kaggle/input/home-value-insights

In [5]:
df = pd.read_csv(f'{path}/house_price_regression_dataset.csv')
df.head()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06

In [6]:
df.shape

(1000, 8)

In [8]:
df.isnull().sum()

Square_Footage          0
Num_Bedrooms            0
Num_Bathrooms           0
Year_Built              0
Lot_Size                0
Garage_Size             0
Neighborhood_Quality    0
House_Price             0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.columns

Index(['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms', 'Year_Built',
       'Lot_Size', 'Garage_Size', 'Neighborhood_Quality', 'House_Price'],
      dtype='object')

In [14]:
x = df[['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms', 'Year_Built',
       'Lot_Size', 'Garage_Size', 'Neighborhood_Quality']]

y = df[['House_Price']]

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [16]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [17]:
predict = model.predict(x_test)
predict

array([[ 868687.10747903],
       [ 490337.89825447],
       [ 945667.12422537],
       [1033402.87599247],
       [ 776698.77390587],
       [ 732444.09335308],
       [ 995051.99156272],
       [ 885174.76924362],
       [ 796730.53817137],
       [ 931741.09209272],
       [ 759486.73376772],
       [ 645409.40410205],
       [ 217706.20688729],
       [1047436.52669427],
       [ 536985.283711  ],
       [ 187868.55343105],
       [ 456819.02346557],
       [ 357933.98497768],
       [ 743138.35721931],
       [ 362670.94796792],
       [ 775101.05248527],
       [ 478174.42921702],
       [ 680966.06345079],
       [ 889457.56001471],
       [ 447158.93387226],
       [ 396997.78641332],
       [ 454334.22026962],
       [ 442837.53540887],
       [ 187336.81096629],
       [ 491668.18070411],
       [ 279715.81740979],
       [ 895941.0005743 ],
       [ 783583.19778842],
       [ 352212.91737968],
       [ 479313.284656  ],
       [ 766612.6601435 ],
       [ 474636.25109508],
       [ 572446.37288032],
       [ 303449.70619643],
       [ 154599.27036073],
       [ 304341.05092125],
       [ 299677.00775284],
       [ 508575.91105888],
       [ 309977.51725285],
       [1082131.76994762],
       [1011343.63575232],
       [ 760359.56460958],
       [ 807425.57445877],
       [1025548.17009414],
       [ 692212.56393101],
       [ 282589.94240716],
       [ 753107.78598704],
       [ 812615.71007891],
       [ 717618.32372696],
       [ 542152.84832665],
       [ 802743.49807682],
       [ 174572.00320684],
       [ 331617.63053122],
       [ 715523.48246119],
       [ 217505.88982089],
       [ 985804.5902999 ],
       [ 375877.18130299],
       [ 321235.45278182],
       [ 511200.19220676],
       [ 615059.25167579],
       [ 558400.66921077],
       [ 476020.6931617 ],
       [ 746343.25194325],
       [ 951016.94354083],
       [ 742469.14020185],
       [ 473296.834693  ],
       [ 860886.66312621],
       [ 265113.04482733],
       [ 580312.16824127],
       [ 674220.08860653],
       [ 730098.34109805],
       [ 549526.7813823 ],
       [ 198305.11522801],
       [ 540249.2659329 ],
       [ 881855.57285031],
       [ 545130.76007829],
       [ 415897.84088341],
       [ 536816.29690278],
       [ 198562.83178418],
       [ 152224.2165511 ],
       [ 357347.11900056],
       [ 966222.00027834],
       [ 940575.03330627],
       [ 542802.18518943],
       [ 232537.83832164],
       [ 933085.15094735],
       [ 778059.57603192],
       [ 358039.8152377 ],
       [ 800708.86111662],
       [ 702393.31631872],
       [1059729.01759691],
       [ 761426.53314906],
       [ 889365.97173648],
       [ 854927.74547478],
       [ 597198.6834406 ],
       [ 911269.21092922],
       [ 863069.25810309],
       [ 271456.90213362],
       [ 615152.96239634],
       [ 444828.80584085],
       [ 925695.45249901],
       [ 572364.24245748],
       [ 205772.00581769],
       [ 280458.16201435],
       [1035178.77456074],
       [ 818936.44883316],
       [ 415693.35207896],
       [ 926085.68296564],
       [ 548202.05250928],
       [ 738072.99323824],
       [ 909764.27325626],
       [ 280749.31446032],
       [ 870859.13014814],
       [ 237403.44567456],
       [ 723833.08956951],
       [ 252753.73839431],
       [ 492142.53742949],
       [ 870751.8129368 ],
       [ 228202.86501912],
       [ 334319.06828666],
       [ 303274.11259537],
       [ 552673.50294364],
       [ 844324.9810864 ],
       [ 957382.94699163],
       [ 588446.07096912],
       [ 777943.95500498],
       [ 685054.84678851],
       [ 614723.93364117],
       [ 698042.53154537],
       [ 686005.22083082],
       [ 857091.10348325],
       [ 516576.27515655],
       [ 621079.90026635],
       [ 665183.15299002],
       [ 244965.46051985],
       [ 490637.33615804],
       [ 864323.62653231],
       [ 340826.51636073],
       [ 736321.81154618],
       [ 879686.58945608],
       [ 351296.2484826 ],
       [ 937440.52504873],
       [ 360704.09163038],
       [ 690896.81145093],
       [ 934727.62835466],
       [ 575392.35274076],
       [ 794279.4271391 ],
       [ 942066.28714163],
       [ 891363.30664496],
       [1052660.81442933],
       [ 687547.88022961],
       [ 273432.67174595],
       [ 636799.84789192],
       [ 981949.27236112],
       [ 754716.67992306],
       [ 241338.21735316],
       [ 863468.78251663],
       [ 811235.28987829],
       [ 668250.51747402],
       [1011917.10218455],
       [ 961827.40341599],
       [ 917379.80420907],
       [ 182078.62387976],
       [ 647382.58157706],
       [ 860385.78718845],
       [ 654445.55121279],
       [ 260417.86071233],
       [ 504865.24895971],
       [ 460371.35050554],
       [ 524605.4419579 ],
       [ 503498.62244532],
       [ 623507.66541628],
       [1028679.70880354],
       [ 673923.19846892],
       [ 527518.52162165],
       [1000741.00495336],
       [ 745598.16667686],
       [ 334756.09411243],
       [ 437468.8526197 ],
       [ 553946.62025399],
       [ 496942.19507049],
       [ 356054.4903897 ],
       [ 606021.46111248],
       [ 569924.55399642],
       [ 331310.39159945],
       [ 506153.51958511],
       [ 492795.16574588],
       [ 962952.26824064],
       [ 926827.79779341],
       [ 258306.50503326],
       [ 818330.78332435],
       [ 167184.46890833],
       [ 974935.37688809],
       [ 440553.82209117],
       [ 663288.68856482]])

In [18]:
score = r2_score(y_test, predict)
score*100

99.84263636823408

In [19]:
import pickle
pickle.dump(model, open('model.pkl', 'wb'))

print("PKL File Created")

PKL File Created